services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/urls.db:/app/urls.db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend